# Generated by Django 3.1.2 on 2020-10-09 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='moneyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderAmount', models.IntegerField(default=0)),
                ('orderCreatedBy', models.EmailField(max_length=60)),
                ('orderApprovedBy', models.EmailField(default='notdoneyet@gmail.com', max_length=60)),
                ('orderCouponCode', models.CharField(default='00', max_length=30)),
                ('orderStatus', models.BooleanField(default=False)),
                ('orderMode', models.CharField(default='NONE', max_length=30)),
                ('orderRemark', models.CharField(default='InProgress', max_length=60)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('isApproved', models.BooleanField(default=False)),
                ('From', models.CharField(default='NULL', max_length=60)),
                ('type', models.CharField(default='CREDIT', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policyNumber', models.CharField(max_length=60)),
                ('policyHolderName', models.CharField(max_length=60)),
                ('amount', models.FloatField(default=None)),
                ('dueDate', models.CharField(max_length=30)),
                ('createdBy', models.EmailField(max_length=60)),
                ('approvedBy', models.EmailField(default='fake@gmail.com', max_length=60)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AccountAdmin',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='order.order')),
            ],
            bases=('order.order',),
        ),
    ]
